steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hippoapp:$COMMIT_SHA', '.']
    dir: 'agentspace-app'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hippoapp:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hippoapp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hippoapp:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'hippoapp-service@lucid-inquiry-453823-b0.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=lucid-inquiry-453823-b0,GCP_STORAGE_BUCKET=language-learning-audio'

images:
  - 'gcr.io/$PROJECT_ID/hippoapp:$COMMIT_SHA'
